project:
  type: website
  output-dir: _site
  
website:
  title: "Huber Group @ EMBL"
  open-graph:
     locale:
       en_US
     site-name:
       "Huber Group @ EMBL"
  navbar:
    background: "#18974C"
    foreground: "#D0DEBB"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Approach & Outputs
      - workwithus.qmd
      - people.qmd
      - posts.qmd
      - events.qmd
      - pub.qmd
      - contact.qmd

format:
  html:
    theme: journal
    linkcolor: "#2A57A3"
    toc-color: "#2A57A3"
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 750px
      margin-width: 300px
    date-format: iso

execute:
  freeze: auto

# 
# EMBL colors: https://www.embl.org/guidelines/design/design-guidelines/colours/
