project:
  type: website
  output-dir: docs

execute:
  enabled: true
  freeze: true
  
engine: knitr
 
website:
  title: "Reliable AI Lab"
  open-graph:
     locale:
       en_US
     site-name:
       "Reliable AI Lab"
  navbar:
    background: "#FAFAFA"
    foreground: "#444444"
    search: true
    left:
      - href: index.html
        text: "Home"
      - href: research.qmd
        text: "Projects"
      - workwithus.qmd
      - people.qmd
      - posts.qmd
      - contact.qmd
 
format:
  html:
    theme:
      - materia
    linkcolor: "#4994EC"
    toc-color: "#4994EC"
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 750px
      margin-width: 300px
    date-format: iso
    include-in-header:
      - text: |
          <meta http-equiv="Cache-Control" content="max-age=1800, must-revalidate"> 
    lightbox: true

resources:
  - pub_raw.html
    
# 
# UZH colors: https://www.cd.uzh.ch/en/elements.html#UZH_Colors
