project:
  type: website

website:
  title: "Huber Group @ EMBL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - pub.qmd
      - people.qmd
      - workwithus.qmd
      - contact.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

execute:
  freeze: auto
