project:
  type: website
  output-dir: _site
  
website:
  title: "Huber Group @ EMBL"
  open-graph:
     locale:
       en_US
     site-name:
       "Huber Group @ EMBL"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Approach & Outputs
      - workwithus.qmd
      - people.qmd
      - posts.qmd
      - events.qmd
      - pub.qmd
      - contact.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 750px
      margin-width: 300px

execute:
  freeze: auto
