project:
  type: website

website:
  title: "Huber Group @ EMBL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - pub.qmd
      - people.qmd
      - workwithus.qmd
      - contact.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 600px
      margin-width: 400px

execute:
  freeze: auto
