---
title: "People"
listing:
  contents: people
  type: grid
  sort: "title asc"
  date-format: "YYYY-MM-DD"
  grid-columns: 4
  grid-item-border: true
  grid-item-align: left
  categories: true
  sort-ui: false
  filter-ui: false
  id: currentpeople
page-layout: full
title-block-banner: false
format:
  html:
    tbl-cap-location: bottom
---
<!-- https://quarto.org/docs/websites/website-listings -->

::: {#currentpeople}
:::

### Alumni

| Name                     | What they did with us | Where they are now |
| ------------------------ | --------------------- | ---------------------------------------------- |
| **Ashkan Karimi Saber**  | Master internship | |
| **Ming Yi**              | Master thesis | |
| **Spyridon Giagtzoglou** | Master thesis | [PhD Candidate](https://www.maastrichtuniversity.nl/cs-giagtzoglou) at Maastricht University, The Netherlands |
| **Sophie Tascedda**      | Master internship | PhD candidate at University Hospital Lausanne, Lausanne, Switerland |
| **David Pomerenke**      | Master thesis     | Data Scientist at Federal Ministry for Economic Cooperation and Development, Berlin, Germany|
| **Thomas Bahne**         | Master thesis     | |
| **Jannik Wirtz**         | Master thesis     | AI and Computer Vision at Caterra, Zurich, Switzerland |
| **Caio Guirado**         | Master thesis     | Applied Scientist at Uber, Amsterdam, The Netherlands |
| **Magnus Kinder**        | Master thesis     | Data Scientist at Valkuren, Brussels, Belgium |
| **Kristian van Kuijk**   | Bachelor thesis, Master internship, Master thesis | ASML, Eindhoven, The Netherlands |
| **Marco Guazzini**       | Master internship, Master thesis | APG Asset Management, Amsterdam, The Netherlands |
| **Philip Randall**       | Master thesis     | Analytics Engineer at Instaffo, Heidelberg, Germany |
| **Alexander Reisach**    | Master internship, Master thesis | [PhD Candidate](https://scriddie.github.io) at Université Paris Cité, Paris, France |
