---
title: "Working With Us"
---

### Current Openings

If we are hiring for a specific position, we will post it here.

### Your Own Idea

There are always opportunities for visiting bachelor and master students, PhD candidates, and postdocs to submit your own grants and receive funding for your own ideas. We'd love to hear from you to discuss ideas!

Here some recurring funding sources:

* Digital Society Initiative [Excellence Program (PhD)](https://www.dsi.uzh.ch/en/education/excellence-program/)
* University of Zurich [funding for postocs](https://www.research.uzh.ch/en/funding/postdoc.html#1_Research_at_UZH)
* Visiting students [traineeships](https://www.int.uzh.ch/en/in/traineeships_STREAM/finances-semp.html)

Please contact Christof Seiler with your CV and why you would like to join our group. 

### Graduate School

Please note that we usually recruit PhD candidates via the [PhD program in Epidemiology and Biostatistics](https://www.epibiostat-phd.uzh.ch/en.html). Feel free to contact Christof Seiler to discuss your application before you apply to the graduate school.
