name: Deploy to S3 with Quarto

on:
  push:
    branches:
      - automated_branch # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # 2. Set up Docker container with Quarto
    - name: Set up Docker
      run: |
        docker run -d --name quarto-container -v "$(pwd)":/project rocker/verse tail -f /dev/null

        docker exec quarto-container R -e "install.packages('kableExtra', repos='http://cran.rstudio.com/')"

    # 4. Get the citation counts
    - name: Run R script to get citation counts
      run: |
          docker exec quarto-container R rscripts/get_citation_counts.R

    # 5. Renew the existing citation_counts.rds file
    - name: Commit and push changes if any
      run: |
          git remote show origin
          git add citation_counts.rds
          git commit -m "Automatic update of citation counts on $(date -I)" || echo "No changes to commit"
          git push -o ci.skip "https://x-access-token/${{ secrets.GITHUB_TOKEN }}@github.com/Huber-group-EMBL/Huber-group-EMBL.github.io" HEAD:automated_branch || echo "No changes to commit"

    # 6. Render the Quarto project
    - name: Render Quarto project
      run: |
        docker exec quarto-container R --version
        docker exec quarto-container quarto render /project --cache-refresh
        ls -l _site

#     7. Setup MinIO client
    - name: Setup MinIO client
      uses: lovellfelix/minio-deploy-action@v1
      with:
        endpoint: https://s3.embl.de/
        access_key: ${{ secrets.MINIO_ACCESS_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'intercept-testing'
        source_dir: '_site'

    # 8. Clean up Docker container
    - name: Clean up Docker container
      run: |
        docker stop quarto-container
        docker rm quarto-container
